# Generated by Django 2.0.10 on 2019-02-20 10:16

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('df_goods', '0002_auto_20181218_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsinfo',
            name='gcontent',
            field=tinymce.models.HTMLField(max_length=500, verbose_name='详情'),
        ),
        migrations.AlterField(
            model_name='goodsinfo',
            name='gtitle',
            field=models.CharField(max_length=20, unique=True, verbose_name='商品名称'),
        ),
        migrations.AlterField(
            model_name='goodsinfo',
            name='gunit',
            field=models.CharField(max_length=20, verbose_name='浏览量'),
        ),
    ]
