# Generated by Django 2.0.10 on 2019-02-20 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('df_order', '0002_auto_20181218_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='pay_method',
            field=models.SmallIntegerField(choices=[(1, '货到付款'), (2, '微信支付'), (3, '支付宝'), (4, '银联支付')], default=3, verbose_name='支付方式'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='oIsPay',
            field=models.SmallIntegerField(choices=[(1, '待支付'), (2, '代发货'), (3, '待收货'), (4, '待评价'), (5, '已完成')], default=1, verbose_name='订单状态'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='oid',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='订单编号'),
        ),
    ]
